brew/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib import admin

from . import views


app_name = 'brew'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('brew/', views.new_brew, name='new_brew'),
    path('roast/', views.new_roast, name='new_roast'),
    path('register', views.register, name='register'),
    path('brew/<int:brew_id>/', views.brew_profile, name='brew_profile'),
    path('brew/<int:brew_id>/update/', views.update_brew, name='update_brew'),
    path('brew/<int:brew_id>/delete/', views.brew_delete, name='brew_delete'),
    path('roast/<int:roast_id>/', views.roast_profile, name='roast_profile'),
    path('roast/<int:roast_id>/update', views.update_roast, name='update_roast'),
    path('roast/<int:roast_id>/delete', views.roast_delete, name='roast_delete'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),



]

brew/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.utils import timezone

STARS = ((1,'★'),(2,'★★'),(3,'★★★'),(4,'★★★★'),(5,'★★★★★'))
ROAST_CHOICES=((1,'Light'),(2,'Medium'),(3,'Dark'),(4,'Unknown'))
METHOD_CHOICES=((1,'Pour Over'),(2,'Aero Press'),(3,'French Press'),(4,'Drip'),(5,"Unknown"))
ORIGIN=(
	(None, 'Country of Origin'),
    ('Africa', (
            ('kenya', 'Kenya'),
            ('ethiopia', 'Ethiopia'),
            ('burundi', 'Burundi'),
            ('rowanda', 'Rowanda'),
            ('other_africa','Other Africa')
        )
    ),
    ('Central America', (
            ('costa_rica', 'Costa Rica'),
            ('el_salvado', 'El Salvador'),
            ('guatemala', 'Guatemala'),
            ('honduras', 'Honduras'),
            ('panama', 'Panama'),
            ('mexico', 'Mexico'),
            ('nicaragua', 'Nicaragua'),
        )
    ),
    ('South America',(
        ('brazil', 'Brazil'),
        ('bolivia', 'Bolivia'),
        ('colombia','Colombia'),

        )
    ),
    ('Far East',(
        ('bali','Bali'),
        ('papua_new-guinea', 'Papua New Guinea'),
        ('sumatra', 'Sumatra'),
        ('thailand', 'Thailand'),
        ('java', 'Java'),
        ('myanmar', 'Mayanmar'),
        ('vietnam', 'Vietnam'),
        )
    ),
)

class Roast(models.Model):
    origin = models.CharField(max_length=50, null=True, blank=True, choices=ORIGIN)
    roast_name = models.CharField(max_length=200, null=True, blank=True)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    batch_size = models.CharField(max_length=20, null=True, blank=True)
    roast_time = models.CharField(max_length=20, null=True, blank=True)
    roast_levels = models.IntegerField(choices=ROAST_CHOICES, default=1)
    first_crack_start = models.CharField(max_length=20, null=True, blank=True)
    first_crack_end = models.CharField(max_length=20,null=True, blank=True)
    second_crack_start = models.CharField(max_length=20, null=True, blank=True)
    notes = models.TextField(max_length=200, blank=True, null=True)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.roast_name

class Acidity(models.Model):
    acidity = models.CharField(max_length=200)
    def __str__(self):
        return self.acidity

class Flavor(models.Model):
    flavor = models.CharField(max_length=200)
    def __str__(self):
        return self.flavor

class Brew(models.Model):
    coffee_name = models.CharField(max_length=200)
    roastery = models.CharField(max_length=200, null=True, blank=True)
    pub_date = models.DateTimeField(blank=True, null=True)
    roast_levels = models.IntegerField(choices=ROAST_CHOICES, default=1)
    methods = models.IntegerField(choices=METHOD_CHOICES, default=1)
    acidity = models.ManyToManyField(Acidity, blank=True)
    flavor = models.ManyToManyField(Flavor, blank=True)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    home_roast = models.ForeignKey('Roast', blank=True, null=True, on_delete=models.CASCADE)
    stars = models.IntegerField(default=3, choices=STARS)
    def __str__(self):
        return self.coffee_name

    def publish(self):
        self.pub_date = timezone.now()
        self.save()



# Create your models here.((1,'Fruity'),(2,'Sweet'),(3,'Nutty'),(4,'Woody'),(5,'Malty'),(6,'Vanilla'),(7,'Caramel')(8,'Chocolate'),(9,'Bitter'),(10,'Clove'))

brew/forms.py
from django import forms
from django.forms import ModelForm, CheckboxSelectMultiple, RadioSelect, SelectMultiple
from brew.models import Brew, Roast, Acidity, Flavor


class BrewForm(ModelForm):
	class Meta:
		model = Brew
		fields='__all__'
		widgets = {
			'roast_levels': RadioSelect(),
			'methods': RadioSelect(),
			'acidity': CheckboxSelectMultiple(),
			'flavor': CheckboxSelectMultiple(),
			'stars': RadioSelect(),
		}
	def __init__(self, user, *args, **kwargs):
		super(BrewForm, self).__init__(*args, **kwargs)
		self.fields['home_roast'].queryset = Roast.objects.filter(user=user)

class RoastForm(ModelForm):
	class Meta:
		model = Roast
		exclude = ['user']
		widgets ={
			'roast_levels': RadioSelect(),
		}

brew/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import UpdateView
from django.utils import timezone


from .forms import BrewForm, RoastForm
from .models import Brew, Roast, Acidity, Flavor


def index(request):
    return render(request,'brew/index.html')

@login_required
def new_brew(request):
    if request.method == 'POST':
        form = BrewForm(request.user, request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.pub_date = timezone.now()
            obj.save()
            form.save_m2m()
            return redirect('brew:profile')
    else:
        form = BrewForm(request.user)
    return render(request, 'brew/new_brew.html', {'form': form})

@login_required
def update_brew(request, brew_id):
    brew = get_object_or_404(Brew, pk=brew_id)
    if request.method == "POST":
        form = BrewForm(request.user, request.POST, instance=brew)
        if form.is_valid():
            brew = form.save(commit=False)
            brew.user = request.user
            brew.pub_date = timezone.now()
            brew.save()
            form.save_m2m()
            return redirect('brew:brew_profile', brew_id)
    else:
        form = BrewForm(request.user, instance=brew)
    return render(request, 'brew/brew_update_form.html', {'form': form})

@login_required
def brew_delete(request, brew_id):
    brew = get_object_or_404(Brew, pk=brew_id)
    if request.method == 'POST':
        brew.delete()
        return HttpResponseRedirect("/profile/")
    return render(request, 'brew/brew_confirm_delete.html', {'brew': brew})


@login_required
def brew_profile(request, brew_id):
    brew = get_object_or_404(Brew, pk=brew_id)
    return render(request,'brew/brew_profile.html', {'brew': brew})

@login_required
def new_roast(request):
    if request.method =='POST':
        form = RoastForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            form.save_m2m()
            return redirect('brew:profile')
    else:
        form = RoastForm()
    return render(request, 'brew/new_roast.html', {'form': form})

@login_required
def roast_profile(request, roast_id):
    roast = get_object_or_404(Roast, pk=roast_id)
    return render(request, 'brew/roast_profile.html', {'roast': roast})

@login_required
def update_roast(request, roast_id):
    roast = get_object_or_404(Roast, pk=roast_id)
    if request.method == "POST":
        form = RoastForm(request.POST, instance=roast)
        if form.is_valid():
            roast = form.save(commit=False)
            roast.user = request.user
            roast.save()
            form.save_m2m()
            return redirect('brew:roast_profile', roast_id)
    else:
        form = RoastForm(instance=roast)
    return render(request, 'brew/roast_update_form.html', {'form': form})

@login_required
def roast_delete(request, roast_id):
    roast = get_object_or_404(Roast, pk=roast_id)
    if request.method == 'POST':
        roast.delete()
        return HttpResponseRedirect("/profile/")
    return render(request, 'brew/roast_confirm_delete.html', {'roast': roast})

@login_required
def profile(request):
    brew_list = Brew.objects.filter(user=request.user).order_by('-pub_date')[:10]
    roast_list = Roast.objects.filter(user=request.user).order_by('-pub_date')
    return render(request, 'brew/profile.html', {'brew_list': brew_list, 'roast_list': roast_list})

def register(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = UserCreationForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            registered = True
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=raw_password)
            login(request, user)
            return redirect('brew:profile')
        else:
            print('error')
    else:
        form = UserCreationForm()

    return render(request, 'brew/register.html', {'form': form})

brew/templates/brew/brew_confirm_delete.html
{% extends "base.html" %}
{% load static %}
{% block cssContent %}
<style>
    
    #base {
        background-image: url("{% static 'brew/images/bluebeans.jpg' %}");
          background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
    }

	div h4{
		letter-spacing: 0px!important;
		margin-bottom: 0px;
	}
	div p{
		color: #c1c1c1;
	}
</style>
{% endblock %}
{% block content %}
<div class='container-fluid login-box brew-box justify-content-center center'>
    <div class='row text-center justify-content-center'>
		<form method="post">{% csrf_token %}
    		<h4>Are you sure you want to delete {{ brew.coffee_name }}?</h4>
   			 <input class= 'clear-login-button' type="submit" value="Confirm">
		</form>
	</div>
	<div style = 'margin-bottom: 10px;' class='row justify-content-center'>
		<a class='link' href="{% url 'brew:brew_profile' brew.id %}"> Back</a>

	</div>
</div>
{% endblock %}

brew/templates/brew/brew_profile.html
{% extends "base.html" %}
{% load static %}
{% block cssContent %}
<style>
    
    #base {
        background-image: url("{% static 'brew/images/bluebeans.jpg' %}");
          background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
    }

	div h4{
		letter-spacing: 0px!important;
		margin-bottom: 0px;
	}
	div p{
		color: #c1c1c1;
	}
</style>
{% endblock %}
{% block content %}
<div class='container-fluid login-box justify-content-center center brew-box'>
	<div style = 'margin-bottom: 10px;' class='row justify-content-start'>
		<a class='link' href="{% url 'brew:profile' %}"> Back</a>
	</div>
    <div class='row text-center justify-content-center'>
    	
        <h2>{{brew.coffee_name}}</h2>
    </div>
    <hr>
    <div class="row justify-content-center">
        <h3>{% if brew.home_roast %}
            		by {{brew.home_roast}}
            	{% else %}
            		{{brew.roastery}}
            	{% endif %}
        </h3>

    </div>
    
	<div class='row' style='padding-top: 20px;'>
       <div class = 'col text-left'>
       	<h4>Roast Level:</h4>
		<p>{{brew.get_roast_levels_display}}</p>
		</div>
		<div class = 'col text-left'>
			<h4>Method:</h4>
			<p>{{brew.get_methods_display}}</p>
		</div>
        
                
    </div>
    <div class='row'>
        <div class = 'col text-left'>
       		<h4>Flavor Notes:</h4>
       		{% if brew.flavor.all %}
                {% for flavor in brew.flavor.all %}
        		<p style='margin-bottom: 0;'>{{flavor}}</p>
                {% endfor %}
        	{% else %}
        		<p>Tasted like coffee.</p>
        	{% endif %}
    	</div>

        <div class="col text-left">
        	<h4>Acidity Notes:</h4>
        	 {% if brew.acidity.all %}
                {% for acidity in brew.acidity.all %}
        		<p style='margin-bottom: 0;'>{{acidity}}</p>
                {% endfor %}
        	{% else %}
        		<p>Nothing to note.</p>
        	{% endif %}
    	</div>
    </div>
    <div class='row text-center'>

	<a class= 'clear-login-button' href="{% url 'brew:update_brew' brew.id %}"> Edit</a>
	</div>
	<div class='row justify-content-center'>
	<a class='link' href="{% url 'brew:brew_delete' brew.id %}"> Delete</a>
	</div>
           
</div><!--container-->



{% endblock %}

brew/templates/brew/brew_update_form.html
{% extends "brew/new_brew.html" %}

brew/templates/brew/index.html
{% extends "base.html" %}
{% load static %}

{% block cssContent %}
<style>
	.bluebeans {
		background-image: linear-gradient(
            rgba(0, 0, 0, 0.5),
            rgba(0, 0, 0, 0.5)
            ),url("{% static 'brew/images/bluebeans.jpg' %}");
		background-repeat: no-repeat;
    	background-size: cover;
    	background-position: center;
    	box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.25);
    	height: 50%;

	}
	.pourover{
		background-image: url("{% static 'brew/images/pourover.jpg' %}");
		background-repeat: no-repeat;
    	background-size: cover;
    	background-position: center;
    	box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.25);
    	margin-bottom: 50px;
		max-height: 75%;

	}
	.pourover:hover{
		background-image: linear-gradient(
            rgba(0, 0, 0, 0.5),
            rgba(0, 0, 0, 0.5)
            ),url("{% static 'brew/images/pourover.jpg' %}");
	}
	.beanjar{
		background-image: url("{% static 'brew/images/beanjar.jpg' %}");
		background-repeat: no-repeat;
    	background-size: cover;
    	background-position: center;
    	box-shadow: 0px 10px 10px rgba(0, 0, 0, 0.25);
    	margin-bottom: 50px;
    	max-height: 75%;

	}
	.beanjar:hover{
		background-image: linear-gradient(
            rgba(0, 0, 0, 0.5),
            rgba(0, 0, 0, 0.5)
            ),url("{% static 'brew/images/beanjar.jpg' %}");
	}




</style>
{% endblock %}

{% block content %}
<div class = 'jumbotron bluebeans'>
	<div class='container'>
		<div style='padding-bottom:30px' class = 'row d-flex justify-content-end'>
			<button class='clear-button'><a href="{% url 'brew:register' %}">Create an account</a>
			</button>
			<button class='clear-button' id='white-button'> <a href="{% url 'brew:login' %}">Log in</a></button>
		</div>
		<div class='row d-flex justify-content-center'>

					<h1>Coffee Tracker</h1>
		</div>
		<div class='row d-flex justify-content-center'>
					<h3>Log Roasts . Rate Brews</h3>

		</div>

	</div>
</div>
<a href="{% url 'brew:login' %}">
<div class='container d-flex h-100 justify-content-center pourover'>
	<div class='row align-self-center'>
		<h2>Brew</h2>
	</div>
</div>
</a>
<a href="{% url 'brew:login' %}">
<div class='container d-flex h-100 justify-content-center beanjar'>
	<div class='row align-self-center'>
		<h2>Roast</h2>
	</div>
</div>
</a>




{% endblock %}

brew/templates/brew/new_roast.html
{% extends "base.html" %}
{% load static %}
{% block cssContent %}
<style>
    
    #base {
        background-image: url("{% static 'brew/images/bluebeans.jpg' %}");
          background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
    }
    div .row{
        margin-bottom: 20px;
    }
    #id_notes{
        width:100%;
    }
</style>
{% endblock %}
{% block content %}
<div class='container-fluid login-box justify-content-center center brew-box'>
    <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            <div class='row text-center'>
                <div class="col form-title text-center">
                    {{ form.roast_name.errors }}
                    {{ form.roast_name.label_tag }}
                </div>
                <div class="col text-center input-box">
                    {{ form.roast_name }}
                </div>
            </div>
            <div class='row'>
                <div class="col form-title text-center">
                    {{ form.origin.errors }}
                    {{ form.origin.label_tag }}
                </div>
                <div class="col text-center input-box">
                    {{ form.origin }}
                </div>
            </div>
            <div class='row'>
                <div class="col form-title text-center">

                    {{ form.batch_size.errors }}
                    {{ form.batch_size.label_tag }}
                </div>
                <div class="col text-center input-box">
                    {{ form.batch_size }}
                </div>
            </div>
            <div class='row'>
                <div class="col form-title text-center">

                    {{ form.roast_time.errors }}
                    {{ form.roast_time.label_tag }}
                </div>
                <div class="col text-center input-box">
                    {{ form.roast_time }}
                </div>
            </div>
            <div class='row form-title justify-content-center'>
                <div class="col text-center">
    
                    
                        {{ form.roast_levels.errors }}
                        {{ form.roast_levels.label_tag }}
                </div>
                <div class="col text-left">
                        {% for level in form.roast_levels %}
                
                        <span>{{ level }}<br></span>
                
                        {% endfor %}
                </div>    
            </div>
            <div class='row'>
                <div class="col form-title text-center">

                    {{ form.first_crack_start.errors }}
                    {{ form.first_crack_start.label_tag }}
                </div>
                <div class="col text-center input-box">
                    {{ form.first_crack_start }}
                </div>
            </div>
            <div class='row'>
                <div class="col form-title text-center">

                    {{ form.first_crack_end.errors }}
                    {{ form.first_crack_end.label_tag }}
                </div>
                <div class="col text-center input-box">
                    {{ form.first_crack_end }}
                </div>
            </div>
            <div class='row'>
                <div class="col form-title text-center">

                    {{ form.second_crack_start.errors }}
                    {{ form.second_crack_start.label_tag }}
                </div>
                <div class="col text-center input-box">
                    {{ form.second_crack_start }}
                </div>
            </div>
            <div class='row'>
                <div class="col form-title">

                    {{ form.notes.errors }}
                    {{ form.notes.label_tag }}
                    <span style='color:black;'>{{ form.notes }}</span>
                </div>
            </div>
        </div>
        <input class='white-submit-button' type="submit" value="Submit">
        <div style = 'margin-top: 20px; margin-bottom: 10px;' class='row justify-content-center'>
        <a class='link' href="{% url 'brew:profile' %}"> Back</a>
    </div>

</form>
</div>
    
{% endblock %}

brew/templates/brew/profile.html
{% extends "base.html" %}
{% load static %}

{% block cssContent %}
<style>
	.hero-image {
		background-image: linear-gradient(
            rgba(0, 0, 0, 0.5),
            rgba(0, 0, 0, 0.5)
            ),url("{% static 'brew/images/coffeestuff.jpg' %}");
		background-repeat: no-repeat;
    	background-size: cover;
    	background-position: center;
    	height: 350px;
    	margin-bottom: 0 !important;
	}

	.header-color{
		background: white;
	}
	.header-size{
		margin:0;
		font-weight:bold;

	}
	#myTab {
		background-color: #F5F4F4;
		font-size: 18px;
		box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.28);
	}
	#myTab a{
		color: #787978;

	}
	#myTab li.active a{
		border-bottom: 5px solid #04D5FD;
		color:black;
	}
	#myTab li a{
		padding:10px 30px;
	}

	.navbar{
		height: 20px !important;
		margin-bottom: 0 !important;
		border-bottom: black;
		background-color: #F5F4F4;

		box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.28);


	}
	#navbarSupportedContent li a{
		border-color: black;
		color:black;
		font-size: 12px;
	}


	.profile-list{
		background: rgba(19, 19, 19, 0.26);
	}

	hr {
	border-top: 1px solid #FFFFFF;
	}

	.list-item{
		background: #c79034;
		margin-bottom: 15px;
		box-shadow: 4px 5px 15px rgba(0, 0, 0, 0.25);
	}
	.no-list-item{

		max-height: 100px;
		background: #c79034;
		box-shadow: 4px 5px 15px rgba(0, 0, 0, 0.25);
	}
	.no-list-item:hover{
		background: #af7d2b;
	}
	div button a{
		font-size: 18px;
	}
	.list-container{
		margin-top:10px;


	}
</style>
{% endblock %}
{% block content %}
		<div class = 'jumbotron hero-image d-flex justify-content-start align-items-end'>
			<div class = 'container'>
			<div class='row'>
				<div class='col text-right'>
				<a href="{% url 'brew:logout' %}" style = 'font-size:15px;' class='link'>Log Out</a>
				</div>
			</div>
			<div class='row text-left' style='padding-top:75px'>
				<h1> Coffee Tracker</h1>
			</div>

			<div class='row text-left'>
				<button class='clear-button'><a href="{% url 'brew:new_brew' %}">New Brew</a></button>
				<button class='clear-button'><a href="{% url 'brew:new_roast' %}">New Roast</a></button>
			</div>
		</div>
		</div>
<!-- Nav tabs -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item active">
    <a class="nav-link" id="brew-tab" data-toggle="tab" href="#brew" role="tab" aria-controls="brew" aria-selected="true">Brew</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="roast-tab" data-toggle="tab" href="#roast" role="tab" aria-controls="roast" aria-selected="false">Roast</a>
  </li>
</ul>


<div class="tab-content">
  <div class="tab-pane active" id="brew" role="tabpanel" aria-labelledby="brew-tab">
  	<div class='list-container container'>
  	{% if brew_list %}

			{% for brew in brew_list %}

  			<div class='row list-item' style="padding-top: 20px;">

  					<div class= 'col'>

						<h3>{{brew.coffee_name}}</h3>
						<h4>
						{% if brew.roastery %}
								Roastery: {{brew.roastery}}
							{% else %}
								{% if brew.home_roast %}
									Home Roast: {{brew.home_roast}}

							{% endif %}
							{% endif %}
							</h4>
						<p>{{brew.get_roast_levels_display}} Roast - {{brew.get_methods_display}}</p>
					</div>
					<div class='col d-flex'>
						<p style="align-self: flex-end; margin-bottom:10px;">{{brew.get_stars_display}}</p>
					</div>
					<div class= 'push-md-col d-flex'>
						<span style="align-self: flex-end; margin-bottom:10px; margin-right: 30px;">
						<a style='margin-right: 15px;' class='link' href="{% url 'brew:brew_profile' brew.id %}">View</a>
						<a class='link' href="{% url 'brew:update_brew' brew.id %}">Edit</a>
						</span>
					</div>
			</div>

			{% endfor %}

			{% else %}
			    <a href="{% url 'brew:new_brew' %}">
				<div class='container d-flex h-100 justify-content-center no-list-item'>
					<div class='row text-center align-self-center'>
						<h2>Coffee Please</h2>
					</div>
				</div>
		        </a>

				{% endif %}
		</div>


  	</div>


  <div class="tab-pane" id="roast" role="tabpanel" aria-labelledby="roast-tab">
  <div class='list-container container'>
  	{% if roast_list %}

		{% for roast in roast_list %}

  			<div class='row list-item' style="padding-top: 20px;">
  					<div class= 'col'>

						<h3>{{roast.get_origin_display}} . {{roast.roast_name}}</h3>

						<p>{{roast.get_roast_levels_display}} Roast</p>

					</div>
					<div class= 'push-md-col d-flex'>
						<span style="align-self: flex-end; margin-bottom:10px; margin-right: 30px;">
						<a style='margin-right: 15px;' class='link' href="{% url 'brew:roast_profile' roast.id %}">View</a>
						<a class='link' href="{% url 'brew:update_roast' roast.id %}">Edit</a>
					</span>
					</div>


				</div>

			{% endfor %}

	{% else %}
	    <a href="{% url 'brew:new_roast' %}">
	    <div class='container d-flex h-100 justify-content-center no-list-item'>
			<div class='row align-self-center'>
				<h2>Get Roasting!</h2>
			</div>
	    </div>
	    </a>

	{% endif %}
	</div>
	</div>

</div>

{% endblock %}

brew/templates/brew/roast_profile.html
{% extends "base.html" %}
{% load static %}
{% block cssContent %}
<style>
    
    #base {
        background-image: url("{% static 'brew/images/bluebeans.jpg' %}");
          background-repeat: no-repeat;
        background-size: cover;
        background-position: center;
    }

	div h4{
		letter-spacing: 0px!important;
		margin-bottom: 0px;
	}
	div p{
		color: #c1c1c1;
	}
</style>
{% endblock %}
{% block content %}
<div class='container-fluid login-box justify-content-center center brew-box' style = 'padding-bottom: 20px'>
	<div style = 'margin-bottom: 10px;' class='row justify-content-start'>
		<a class='link' href="{% url 'brew:profile' %}"> Back</a>
	</div>
   
    <div class='row text-center justify-content-center'>
    	
        <h2>{{roast.roast_name}}{{brew.pk}}{{brew.id}}</h2>
    </div>
    <div class='row text-center justify-content-center'>
        
        <h3>{{roast.get_origin_display}}</h3>
    </div>
    <hr>
	<div class='row'>
       <div class = 'col text-left'>
        <h4>Batch Size:</h4>
            <p>{{roast.batch_size}}</p>
        </div>
        <div class = 'col text-left'>
       	<h4>Roast Level:</h4>
		<p>{{roast.get_roast_levels_display}}</p>
		</div>
		<div class = 'col text-left'>
			<h4>Roast Time</h4>
			<p>{{roast.roast_time}}</p>
		</div>              
    </div>
    <div class='row'>
        <div class = 'col text-left'>
       		<h4>First Crack Start:</h4>
             <p>{{roast.first_crack_start}}</p>
    	</div>
        <div class="col text-left">
            <h4>First Crack End</h4>
            <p>{{roast.first_crack_end}}</p>
        </div>
        <div class="col text-left">
        	<h4>Second Crack Start:</h4>
             <p>{{roast.second_crack_start}}</p>
    	</div>
    </div>
    <div class='row text-center justify-content-center'>
        <h4>Notes:</h4>
        <p>{{roast.notes}}</p>
        
    </div>
    <div class='row text-center'>

	<a class= 'clear-login-button' href="{% url 'brew:update_roast' roast.id %}"> Edit</a>
	</div>
	<div class='row justify-content-center'>
	<a class='link' href="{% url 'brew:roast_delete' roast.id %}"> Delete</a>
	</div>
           
</div><!--container-->



{% endblock %}

brew/templates/brew/roast_update_form.html
{% extends "brew/new_roast.html" %}